# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2e84a2e58d86a0bbcc013178a40568465f7530c00cf50e1f16eafab26d2bd5a2dd49483b4a39a2df89f43a4f4e95958b012b36c2cc43428df6d09d8b70915930

test:
  secret_key_base: 2995bcb6165846c93566aa598deac9bf3208f6d8a0520f882c9e5510be22227c27ce8b68ae0974e9e3124dee89dc19bbd55fe3240156f1fcc073c910c02ebac5

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
